packages:
  - packages/*
allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': false
  '@google/genai': false
  esbuild: true
  koffi: false
  node-pty: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
minimumReleaseAgeExclude:
  - '@oh-my-pi/hashline@17.1.0'
  - '@oh-my-pi/omp-stats@17.1.0'
  - '@oh-my-pi/pi-agent-core@17.1.0'
  - '@oh-my-pi/pi-ai@17.1.0'
  - '@oh-my-pi/pi-catalog@17.1.0'
  - '@oh-my-pi/pi-coding-agent@17.1.0'
  - '@oh-my-pi/pi-mnemopi@17.1.0'
  - '@oh-my-pi/pi-natives-darwin-arm64@17.1.0'
  - '@oh-my-pi/pi-natives-darwin-x64@17.1.0'
  - '@oh-my-pi/pi-natives-linux-arm64@17.1.0'
  - '@oh-my-pi/pi-natives-linux-x64@17.1.0'
  - '@oh-my-pi/pi-natives-win32-x64@17.1.0'
  - '@oh-my-pi/pi-natives@17.1.0'
  - '@oh-my-pi/pi-tui@17.1.0'
  - '@oh-my-pi/pi-utils@17.1.0'
  - '@oh-my-pi/pi-wire@17.1.0'
  - '@oh-my-pi/snapcompact@17.1.0'
